// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextBooky.Models;

namespace TextBooky.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TextBooky.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Life Sciences"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Computer Science"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Physical Sciences"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mathematics"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Engineering"
                        });
                });

            modelBuilder.Entity("TextBooky.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TextBooky.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TextBookId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TextBookId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("TextBooky.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TextbookId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("TextbookId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("TextBooky.Models.TextBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TextBooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "David L. Nelson, Michael M. Cox",
                            CategoryId = 1,
                            Description = "Lehninger Principles of Biochemistry is the #1 bestseller for the introductory biochemistry course because it brings clarity and coherence to an often unwieldy discipline, offering a thoroughly updated survey of biochemistry’s enduring principles, definitive discoveries, and groundbreaking new advances with each edition. This new Seventh Edition maintains the qualities that have distinguished the text since Albert Lehninger’s original edition—clear writing, careful explanations of difficult concepts, helpful problem-solving support, and insightful communication of contemporary biochemistry’s core ideas, new techniques, and pivotal discoveries. Again, David Nelson and Michael Cox introduce students to an extraordinary amount of exciting new findings without an overwhelming amount of extra discussion or detail.",
                            ISBN = "978-0716743392",
                            ImageUrl = "/img/Lehninger.jpg",
                            InStock = true,
                            Price = 60.45m,
                            Title = "Lehninger Principles of Biochemistry"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Joseph Albahari, Ben Albahari",
                            CategoryId = 2,
                            Description = "When you have questions about C# 7.0 or the .NET CLR and its core Framework assemblies, this bestselling guide has the answers you need. Since its debut in 2000, C# has become a language of unusual flexibility and breadth, but its continual growth means there's always more to learn. Organized around concepts and use cases, this updated edition provides intermediate and advanced programmers with a concise map of C# and .NET knowledge.Get up to speed on the C# language, from the basics of syntax and variables to advanced topics such as pointers, operator overloading, and dynamic binding Dig deep into LINQ via three chapters dedicated to the topic Explore concurrency and asynchrony, advanced threading, and parallel programming. Work with .NET features, including XML, regular expressions, networking, serialization, reflection, application domains, and security Delve into Roslyn, the modular C# 7.0 compiler-as-a-service.",
                            ISBN = "978-1491987650",
                            ImageUrl = "/img/C7-in-a-nutshell.jpg",
                            InStock = true,
                            Price = 40.55m,
                            Title = "C# 7.0 in a Nutshell"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Travis Norsen",
                            CategoryId = 3,
                            Description = "Authored by an acclaimed teacher of quantum physics and philosophy, this textbook pays special attention to the aspects that many courses sweep under the carpet. Traditional courses in quantum mechanics teach students how to use the quantum formalism to make calculations. But even the best students - indeed, especially the best students - emerge rather confused about what, exactly, the theory says is going on, physically, in microscopic systems. This supplementary textbook is designed to help such students understand that they are not alone in their confusions (luminaries such as Albert Einstein, Erwin Schroedinger, and John Stewart Bell having shared them), to sharpen their understanding of the most important difficulties associated with interpreting quantum theory in a realistic manner, and to introduce them to the most promising attempts to formulate the theory in a way that is physically clear and coherent.",
                            ISBN = "978-3319658667",
                            ImageUrl = "/img/qm-norsen.jpg",
                            InStock = true,
                            Price = 30.00m,
                            Title = "Foundations of Quantum Mechanics"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Manuel Soler Burillo",
                            CategoryId = 5,
                            Description = "The book is divided into three parts, namely: Introduction, The Aircraft, and Air Transportation, Airports, and Air Navigation. The first part is divided in two chapters in which the student must achieve to understand the basic elements of atmospheric flight (ISA and planetary references) and the technology that apply to the aerospace sector, in particular with a specific comprehension of the elements of an aircraft. The second part focuses on the aircraft and it is divided in five chapters that introduce the student to aircraft aerodynamics (fluid mechanics, airfoils, wings, high-lift devices), aircraft materials and structures, aircraft propulsion, aircraft instruments and systems, and atmospheric flight mechanics (performances and stability and control). The third part is devoted to understand the global air transport system (covering both regulatory and economical frameworks), the airports, and the global air navigation system (its history, current status, and future development). The theoretical contents are illustrated with figures and complemented with some problems/exercises. The problems deal, fundamentally, with aerodynamics and flight mechanics, and were proposed in different exams. The course is complemented by a practical approach.",
                            ISBN = "978-1493727759",
                            ImageUrl = "/img/a-engineering.jpg",
                            InStock = true,
                            Price = 16.99m,
                            Title = "Fundamentals of Aerospace Engineering"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Martin Aigner, Gunter M. Ziegler",
                            CategoryId = 4,
                            Description = "Sixth edition. The book is divided into three parts, namely: Introduction, The Aircraft, and Air Transportation, Airports, and Air Navigation. The first part is divided in two chapters in which the student must achieve to understand the basic elements of atmospheric flight (ISA and planetary references) and the technology that apply to the aerospace sector, in particular with a specific comprehension of the elements of an aircraft. The second part focuses on the aircraft and it is divided in five chapters that introduce the student to aircraft aerodynamics (fluid mechanics, airfoils, wings, high-lift devices), aircraft materials and structures, aircraft propulsion, aircraft instruments and systems, and atmospheric flight mechanics (performances and stability and control). The third part is devoted to understand the global air transport system (covering both regulatory and economical frameworks), the airports, and the global air navigation system (its history, current status, and future development). The theoretical contents are illustrated with figures and complemented with some problems/exercises. The problems deal, fundamentally, with aerodynamics and flight mechanics, and were proposed in different exams. The course is complemented by a practical approach.",
                            ISBN = "978-3662572641",
                            ImageUrl = "/img/proofs.jpg",
                            InStock = true,
                            Price = 40.55m,
                            Title = "Proofs from THE BOOK"
                        },
                        new
                        {
                            Id = 6,
                            Author = "John Skeet",
                            CategoryId = 2,
                            Description = "C# in Depth, Fourth Edition is your key to unlocking the powerful new features added to the language in C# 5, 6, and 7. Following the expert guidance of C# legend Jon Skeet, you'll master asynchronous functions, expression-bodied members, interpolated strings, tuples, and much more.",
                            ISBN = "978-1617294532",
                            ImageUrl = "/img/c-in-depth.png",
                            InStock = true,
                            Price = 19.00m,
                            Title = "C# in Depth"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TextBooky.Models.OrderDetail", b =>
                {
                    b.HasOne("TextBooky.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TextBooky.Models.TextBook", "Textbook")
                        .WithMany()
                        .HasForeignKey("TextBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TextBooky.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("TextBooky.Models.TextBook", "Textbook")
                        .WithMany()
                        .HasForeignKey("TextbookId");
                });

            modelBuilder.Entity("TextBooky.Models.TextBook", b =>
                {
                    b.HasOne("TextBooky.Models.Category", "Category")
                        .WithMany("TextBooks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
